// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';

import type {
  CreateCaptchaData,
  CreateCaptchaError,
  CreateCaptchaResponse,
  CreateEmailRecordData,
  CreateEmailRecordError,
  CreateEmailRecordResponse,
  CreateNamespaceData,
  CreateNamespaceError,
  CreateNamespaceResponse,
  CreateSessionData,
  CreateSessionError,
  CreateSessionResponse,
  CreateSmsRecordData,
  CreateSmsRecordError,
  CreateSmsRecordResponse,
  CreateUserData,
  CreateUserError,
  CreateUserResponse,
  DeleteCaptchaData,
  DeleteCaptchaError,
  DeleteCaptchaResponse,
  DeleteEmailRecordData,
  DeleteEmailRecordError,
  DeleteEmailRecordResponse,
  DeleteNamespaceData,
  DeleteNamespaceError,
  DeleteNamespaceResponse,
  DeleteSessionData,
  DeleteSessionError,
  DeleteSessionResponse,
  DeleteSmsRecordData,
  DeleteSmsRecordError,
  DeleteSmsRecordResponse,
  GetCaptchaData,
  GetCaptchaError,
  GetCaptchaResponse,
  GetEmailRecordData,
  GetEmailRecordError,
  GetEmailRecordResponse,
  GetNamespaceData,
  GetNamespaceError,
  GetNamespaceResponse,
  GetSessionData,
  GetSessionError,
  GetSessionResponse,
  GetSmsRecordData,
  GetSmsRecordError,
  GetSmsRecordResponse,
  GetUserData,
  GetUserError,
  GetUserResponse,
  HelloError,
  HelloResponse,
  ListCaptchasData,
  ListCaptchasError,
  ListCaptchasResponse,
  ListEmailRecordsData,
  ListEmailRecordsError,
  ListEmailRecordsResponse,
  ListNamespacesData,
  ListNamespacesError,
  ListNamespacesResponse,
  ListRegionsError,
  ListRegionsResponse,
  ListSessionsData,
  ListSessionsError,
  ListSessionsResponse,
  ListSmsRecordsData,
  ListSmsRecordsError,
  ListSmsRecordsResponse,
  ListUsersData,
  ListUsersError,
  ListUsersResponse,
  LoginByEmailData,
  LoginByEmailError,
  LoginByEmailResponse,
  LoginByPhoneData,
  LoginByPhoneError,
  LoginByPhoneResponse,
  LoginData,
  LoginError,
  LoginResponse,
  RefreshData,
  RefreshError,
  RefreshResponse,
  RegisterByEmailData,
  RegisterByEmailError,
  RegisterByEmailResponse,
  RegisterByPhoneData,
  RegisterByPhoneError,
  RegisterByPhoneResponse,
  RegisterData,
  RegisterError,
  RegisterResponse,
  ResetPasswordData,
  ResetPasswordError,
  ResetPasswordResponse,
  SendEmailData,
  SendEmailError,
  SendEmailResponse,
  SendSmsData,
  SendSmsError,
  SendSmsResponse,
  SignTokenData,
  SignTokenError,
  SignTokenResponse,
  UpdateCaptchaData,
  UpdateCaptchaError,
  UpdateCaptchaResponse,
  UpdateEmailRecordData,
  UpdateEmailRecordError,
  UpdateEmailRecordResponse,
  UpdateNamespaceData,
  UpdateNamespaceError,
  UpdateNamespaceResponse,
  UpdatePasswordData,
  UpdatePasswordError,
  UpdatePasswordResponse,
  UpdateSessionData,
  UpdateSessionError,
  UpdateSessionResponse,
  UpdateSmsRecordData,
  UpdateSmsRecordError,
  UpdateSmsRecordResponse,
  UpdateUserData,
  UpdateUserError,
  UpdateUserResponse,
  VerifyIdentityData,
  VerifyIdentityError,
  VerifyIdentityResponse,
} from './types.gen';

export const client = createClient(createConfig());

/**
 * health check
 */
export const hello = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<HelloResponse, HelloError, ThrowOnError>({
    ...options,
    url: '/hello',
  });
};

/**
 * login with username/phone/email and password
 */
export const login = <ThrowOnError extends boolean = false>(
  options: Options<LoginData, ThrowOnError>
) => {
  return (options?.client ?? client).post<LoginResponse, LoginError, ThrowOnError>({
    ...options,
    url: '/auth/@login',
  });
};

/**
 * login with email and code
 */
export const loginByEmail = <ThrowOnError extends boolean = false>(
  options: Options<LoginByEmailData, ThrowOnError>
) => {
  return (options?.client ?? client).post<LoginByEmailResponse, LoginByEmailError, ThrowOnError>({
    ...options,
    url: '/auth/@loginByEmail',
  });
};

/**
 * login with phone and code
 */
export const loginByPhone = <ThrowOnError extends boolean = false>(
  options: Options<LoginByPhoneData, ThrowOnError>
) => {
  return (options?.client ?? client).post<LoginByPhoneResponse, LoginByPhoneError, ThrowOnError>({
    ...options,
    url: '/auth/@loginByPhone',
  });
};

/**
 * register with username and password
 */
export const register = <ThrowOnError extends boolean = false>(
  options: Options<RegisterData, ThrowOnError>
) => {
  return (options?.client ?? client).post<RegisterResponse, RegisterError, ThrowOnError>({
    ...options,
    url: '/auth/@register',
  });
};

/**
 * register with phone and code
 */
export const registerByPhone = <ThrowOnError extends boolean = false>(
  options: Options<RegisterByPhoneData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    RegisterByPhoneResponse,
    RegisterByPhoneError,
    ThrowOnError
  >({
    ...options,
    url: '/auth/@registerByPhone',
  });
};

/**
 * register with email and code
 */
export const registerByEmail = <ThrowOnError extends boolean = false>(
  options: Options<RegisterByEmailData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    RegisterByEmailResponse,
    RegisterByEmailError,
    ThrowOnError
  >({
    ...options,
    url: '/auth/@registerByEmail',
  });
};

/**
 * sign token
 */
export const signToken = <ThrowOnError extends boolean = false>(
  options: Options<SignTokenData, ThrowOnError>
) => {
  return (options?.client ?? client).post<SignTokenResponse, SignTokenError, ThrowOnError>({
    ...options,
    url: '/auth/@signToken',
  });
};

/**
 * refresh
 */
export const refresh = <ThrowOnError extends boolean = false>(
  options: Options<RefreshData, ThrowOnError>
) => {
  return (options?.client ?? client).post<RefreshResponse, RefreshError, ThrowOnError>({
    ...options,
    url: '/auth/@refresh',
  });
};

/**
 * Create user
 */
export const createUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserData, ThrowOnError>
) => {
  return (options?.client ?? client).post<CreateUserResponse, CreateUserError, ThrowOnError>({
    ...options,
    url: '/users',
  });
};

/**
 * List users
 */
export const listUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ListUsersResponse, ListUsersError, ThrowOnError>({
    ...options,
    url: '/users',
  });
};

/**
 * Find user
 */
export const getUser = <ThrowOnError extends boolean = false>(
  options: Options<GetUserData, ThrowOnError>
) => {
  return (options?.client ?? client).get<GetUserResponse, GetUserError, ThrowOnError>({
    ...options,
    url: '/users/{userId}',
  });
};

/**
 * Update user
 */
export const updateUser = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserData, ThrowOnError>
) => {
  return (options?.client ?? client).patch<UpdateUserResponse, UpdateUserError, ThrowOnError>({
    ...options,
    url: '/users/{userId}',
  });
};

/**
 * Verify identity
 */
export const verifyIdentity = <ThrowOnError extends boolean = false>(
  options: Options<VerifyIdentityData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    VerifyIdentityResponse,
    VerifyIdentityError,
    ThrowOnError
  >({
    ...options,
    url: '/users/{userId}/@verifyIdentity',
  });
};

/**
 * Reset password
 */
export const resetPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetPasswordData, ThrowOnError>
) => {
  return (options?.client ?? client).post<ResetPasswordResponse, ResetPasswordError, ThrowOnError>({
    ...options,
    url: '/users/{userId}/@resetPassword',
  });
};

/**
 * Update password
 */
export const updatePassword = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePasswordData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    UpdatePasswordResponse,
    UpdatePasswordError,
    ThrowOnError
  >({
    ...options,
    url: '/users/{userId}/@updatePassword',
  });
};

/**
 * Create namespace
 */
export const createNamespace = <ThrowOnError extends boolean = false>(
  options: Options<CreateNamespaceData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateNamespaceResponse,
    CreateNamespaceError,
    ThrowOnError
  >({
    ...options,
    url: '/namespaces',
  });
};

/**
 * List namespaces
 */
export const listNamespaces = <ThrowOnError extends boolean = false>(
  options?: Options<ListNamespacesData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ListNamespacesResponse, ListNamespacesError, ThrowOnError>(
    {
      ...options,
      url: '/namespaces',
    }
  );
};

/**
 * Find namespace by id or key
 */
export const getNamespace = <ThrowOnError extends boolean = false>(
  options: Options<GetNamespaceData, ThrowOnError>
) => {
  return (options?.client ?? client).get<GetNamespaceResponse, GetNamespaceError, ThrowOnError>({
    ...options,
    url: '/namespaces/{namespaceIdOrKey}',
  });
};

/**
 * Update namespace
 */
export const updateNamespace = <ThrowOnError extends boolean = false>(
  options: Options<UpdateNamespaceData, ThrowOnError>
) => {
  return (options?.client ?? client).patch<
    UpdateNamespaceResponse,
    UpdateNamespaceError,
    ThrowOnError
  >({
    ...options,
    url: '/namespaces/{namespaceId}',
  });
};

/**
 * Delete namespace
 * Role required: NS_MANAGER
 */
export const deleteNamespace = <ThrowOnError extends boolean = false>(
  options: Options<DeleteNamespaceData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    DeleteNamespaceResponse,
    DeleteNamespaceError,
    ThrowOnError
  >({
    ...options,
    url: '/namespaces/{namespaceId}',
  });
};

/**
 * Create session
 */
export const createSession = <ThrowOnError extends boolean = false>(
  options: Options<CreateSessionData, ThrowOnError>
) => {
  return (options?.client ?? client).post<CreateSessionResponse, CreateSessionError, ThrowOnError>({
    ...options,
    url: '/sessions',
  });
};

/**
 * List sessions
 */
export const listSessions = <ThrowOnError extends boolean = false>(
  options?: Options<ListSessionsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ListSessionsResponse, ListSessionsError, ThrowOnError>({
    ...options,
    url: '/sessions',
  });
};

/**
 * Find session by id
 */
export const getSession = <ThrowOnError extends boolean = false>(
  options: Options<GetSessionData, ThrowOnError>
) => {
  return (options?.client ?? client).get<GetSessionResponse, GetSessionError, ThrowOnError>({
    ...options,
    url: '/sessions/{sessionId}',
  });
};

/**
 * Update session
 */
export const updateSession = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSessionData, ThrowOnError>
) => {
  return (options?.client ?? client).patch<UpdateSessionResponse, UpdateSessionError, ThrowOnError>(
    {
      ...options,
      url: '/sessions/{sessionId}',
    }
  );
};

/**
 * Delete session
 */
export const deleteSession = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSessionData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    DeleteSessionResponse,
    DeleteSessionError,
    ThrowOnError
  >({
    ...options,
    url: '/sessions/{sessionId}',
  });
};

/**
 * Create captcha
 */
export const createCaptcha = <ThrowOnError extends boolean = false>(
  options: Options<CreateCaptchaData, ThrowOnError>
) => {
  return (options?.client ?? client).post<CreateCaptchaResponse, CreateCaptchaError, ThrowOnError>({
    ...options,
    url: '/captchas',
  });
};

/**
 * List captchas
 */
export const listCaptchas = <ThrowOnError extends boolean = false>(
  options?: Options<ListCaptchasData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ListCaptchasResponse, ListCaptchasError, ThrowOnError>({
    ...options,
    url: '/captchas',
  });
};

/**
 * Find captcha by id
 */
export const getCaptcha = <ThrowOnError extends boolean = false>(
  options: Options<GetCaptchaData, ThrowOnError>
) => {
  return (options?.client ?? client).get<GetCaptchaResponse, GetCaptchaError, ThrowOnError>({
    ...options,
    url: '/captchas/{captchaId}',
  });
};

/**
 * Update captcha
 */
export const updateCaptcha = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCaptchaData, ThrowOnError>
) => {
  return (options?.client ?? client).patch<UpdateCaptchaResponse, UpdateCaptchaError, ThrowOnError>(
    {
      ...options,
      url: '/captchas/{captchaId}',
    }
  );
};

/**
 * Delete captcha
 */
export const deleteCaptcha = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCaptchaData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    DeleteCaptchaResponse,
    DeleteCaptchaError,
    ThrowOnError
  >({
    ...options,
    url: '/captchas/{captchaId}',
  });
};

/**
 * Send plain text email
 */
export const sendEmail = <ThrowOnError extends boolean = false>(
  options: Options<SendEmailData, ThrowOnError>
) => {
  return (options?.client ?? client).post<SendEmailResponse, SendEmailError, ThrowOnError>({
    ...options,
    url: '/email/@sendEmail',
  });
};

/**
 * Create email record
 */
export const createEmailRecord = <ThrowOnError extends boolean = false>(
  options: Options<CreateEmailRecordData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateEmailRecordResponse,
    CreateEmailRecordError,
    ThrowOnError
  >({
    ...options,
    url: '/email/records',
  });
};

/**
 * List email records
 */
export const listEmailRecords = <ThrowOnError extends boolean = false>(
  options?: Options<ListEmailRecordsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ListEmailRecordsResponse,
    ListEmailRecordsError,
    ThrowOnError
  >({
    ...options,
    url: '/email/records',
  });
};

/**
 * Find email record by id
 */
export const getEmailRecord = <ThrowOnError extends boolean = false>(
  options: Options<GetEmailRecordData, ThrowOnError>
) => {
  return (options?.client ?? client).get<GetEmailRecordResponse, GetEmailRecordError, ThrowOnError>(
    {
      ...options,
      url: '/email/records/{emailRecordId}',
    }
  );
};

/**
 * Update email record
 */
export const updateEmailRecord = <ThrowOnError extends boolean = false>(
  options: Options<UpdateEmailRecordData, ThrowOnError>
) => {
  return (options?.client ?? client).patch<
    UpdateEmailRecordResponse,
    UpdateEmailRecordError,
    ThrowOnError
  >({
    ...options,
    url: '/email/records/{emailRecordId}',
  });
};

/**
 * Delete email record
 */
export const deleteEmailRecord = <ThrowOnError extends boolean = false>(
  options: Options<DeleteEmailRecordData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    DeleteEmailRecordResponse,
    DeleteEmailRecordError,
    ThrowOnError
  >({
    ...options,
    url: '/email/records/{emailRecordId}',
  });
};

/**
 * List Regions
 */
export const listRegions = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<ListRegionsResponse, ListRegionsError, ThrowOnError>({
    ...options,
    url: '/region',
  });
};

/**
 * Send sms
 */
export const sendSms = <ThrowOnError extends boolean = false>(
  options: Options<SendSmsData, ThrowOnError>
) => {
  return (options?.client ?? client).post<SendSmsResponse, SendSmsError, ThrowOnError>({
    ...options,
    url: '/sms/@sendSms',
  });
};

/**
 * Create sms record
 */
export const createSmsRecord = <ThrowOnError extends boolean = false>(
  options: Options<CreateSmsRecordData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateSmsRecordResponse,
    CreateSmsRecordError,
    ThrowOnError
  >({
    ...options,
    url: '/sms/records',
  });
};

/**
 * List sms records
 */
export const listSmsRecords = <ThrowOnError extends boolean = false>(
  options?: Options<ListSmsRecordsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ListSmsRecordsResponse, ListSmsRecordsError, ThrowOnError>(
    {
      ...options,
      url: '/sms/records',
    }
  );
};

/**
 * Find sms record by id
 */
export const getSmsRecord = <ThrowOnError extends boolean = false>(
  options: Options<GetSmsRecordData, ThrowOnError>
) => {
  return (options?.client ?? client).get<GetSmsRecordResponse, GetSmsRecordError, ThrowOnError>({
    ...options,
    url: '/sms/records/{smsRecordId}',
  });
};

/**
 * Update sms record
 */
export const updateSmsRecord = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSmsRecordData, ThrowOnError>
) => {
  return (options?.client ?? client).patch<
    UpdateSmsRecordResponse,
    UpdateSmsRecordError,
    ThrowOnError
  >({
    ...options,
    url: '/sms/records/{smsRecordId}',
  });
};

/**
 * Delete sms record
 */
export const deleteSmsRecord = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSmsRecordData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    DeleteSmsRecordResponse,
    DeleteSmsRecordError,
    ThrowOnError
  >({
    ...options,
    url: '/sms/records/{smsRecordId}',
  });
};
