// This file is auto-generated by @hey-api/openapi-ts

export type Captcha = {
  /**
   * 验证码
   */
  code: string;
  /**
   * 过期时间
   */
  expireAt: string;
  /**
   * key
   */
  key: string;
  /**
   * Entity id
   */
  id: string;
  /**
   * Entity created at when
   */
  createdAt?: string;
  /**
   * Entity updated at when
   */
  updatedAt?: string;
  /**
   * Entity created by who
   */
  createdBy?: string;
  /**
   * Entity updated by who
   */
  updatedBy?: string;
};

export type CreateCaptchaDto = {
  /**
   * 验证码
   */
  code?: string;
  /**
   * 过期时间
   */
  expireAt?: string;
  /**
   * key
   */
  key: string;
};

export type CreateEmailRecordDto = {
  status: EmailStatus;
  /**
   * 发件者
   */
  from: string;
  /**
   * 收件者
   */
  to: string;
  /**
   * 主题
   */
  subject: string;
  /**
   * 内容
   */
  content: string;
  /**
   * 发送时间
   */
  sentAt?: string;
};

export type CreateGroupDto = {
  /**
   * 额外数据
   */
  data?: string;
  /**
   * 名称
   */
  name: string;
  /**
   * 权限
   */
  permissions?: Array<string>;
  /**
   * 是否启用
   */
  active?: boolean;
  /**
   * 人数
   */
  userCount?: number;
};

export type CreateNamespaceDto = {
  /**
   * 额外数据
   */
  data?: string;
  /**
   * 描述
   */
  desc?: string;
  /**
   * 标签
   */
  labels?: Array<string>;
  /**
   * 名称
   */
  name: string;
  /**
   * 命名空间的 key
   *
   * 允许的字符 ^[a-zA-Z][a-zA-Z0-9._/-]{0,30}$
   */
  key: string;
  /**
   * 所属的 namespace
   */
  ns?: string;
  /**
   * 权限
   */
  permissions?: Array<string>;
  /**
   * 是否启用
   */
  active?: boolean;
  /**
   * 默认密码
   */
  defaultPassword?: string;
  /**
   * 是否可导出
   */
  exportable?: boolean;
  /**
   * 人数
   */
  userCount?: number;
};

export type CreateRoleDto = {
  /**
   * 权限
   */
  permissions?: Array<string>;
  /**
   * role key
   */
  key: string;
  /**
   * 名称
   */
  name: string;
};

export type CreateSessionDto = {
  /**
   * 用户 ID
   */
  uid: string;
  /**
   * 访问控制列表
   */
  acl?: {
    [key: string]: unknown;
  };
  /**
   * 会话过期时间
   */
  expireAt: string;
  /**
   * 客户端/设备
   */
  client?: string;
};

export type CreateSmsRecordDto = {
  status: SmsStatus;
  /**
   * 手机号
   */
  phone: string;
  /**
   * 签名
   */
  sign: string;
  /**
   * 模板
   */
  template: string;
  /**
   * 参数
   */
  params?: string;
  /**
   * 发送时间
   */
  sentAt?: string;
};

export type CreateUserDto = {
  /**
   * 密码
   */
  password?: string;
  /**
   * 是否有密码
   */
  readonly hasPassword?: boolean;
  /**
   * 头像
   */
  avatar?: string;
  /**
   * 额外数据
   */
  data?: string;
  /**
   * 邮箱
   */
  email?: string;
  /**
   * 姓名
   */
  name?: string;
  identity?: string;
  /**
   * 实名认证时间
   */
  identityVerifiedAt?: string;
  /**
   * 实名认证是否通过
   */
  identityVerified?: boolean;
  /**
   * 简介
   */
  intro?: string;
  /**
   * 使用语言
   */
  language?: string;
  /**
   * 昵称
   */
  nickname?: string;
  /**
   * 所属命名空间
   */
  ns?: string;
  /**
   * 手机号
   */
  phone?: string;
  /**
   * 注册地区，存地区编号
   */
  registerRegion?: string;
  /**
   * 角色
   */
  roles?: Array<string>;
  /**
   * 是否超级管理员
   */
  super?: boolean;
  /**
   * 用户名
   */
  username?: string;
  /**
   * 员工编号
   */
  employeeId?: string;
  /**
   * 权限
   */
  permissions?: Array<string>;
  /**
   * 团队
   */
  groups?: Array<string>;
  /**
   * 是否启用
   */
  active?: boolean;
  /**
   * 邀请码
   */
  inviteCode?: string;
  /**
   * 状态
   */
  status?: string;
  /**
   * 过期时间
   */
  expireAt?: string;
  /**
   * 类型，支持设置多个
   */
  types?: Array<string>;
};

export type EmailRecord = {
  status: EmailStatus;
  /**
   * 发件者
   */
  from: string;
  /**
   * 收件者
   */
  to: string;
  /**
   * 主题
   */
  subject: string;
  /**
   * 内容
   */
  content: string;
  /**
   * 发送时间
   */
  sentAt?: string;
  /**
   * Entity id
   */
  id: string;
  /**
   * Entity created at when
   */
  createdAt?: string;
  /**
   * Entity updated at when
   */
  updatedAt?: string;
  /**
   * Entity created by who
   */
  createdBy?: string;
  /**
   * Entity updated by who
   */
  updatedBy?: string;
};

/**
 * 发送状态
 */
export type EmailStatus = 'pending' | 'sent';

export type Group = {
  /**
   * 额外数据
   */
  data?: string;
  /**
   * 名称
   */
  name: string;
  /**
   * 权限
   */
  permissions?: Array<string>;
  /**
   * 是否启用
   */
  active?: boolean;
  /**
   * 人数
   */
  userCount?: number;
  /**
   * Entity id
   */
  id: string;
  /**
   * Entity created at when
   */
  createdAt?: string;
  /**
   * Entity updated at when
   */
  updatedAt?: string;
  /**
   * Entity created by who
   */
  createdBy?: string;
  /**
   * Entity updated by who
   */
  updatedBy?: string;
};

export type HealthCheckResult = {
  message: string;
};

export type Industry = {
  /**
   * 编码
   */
  code: string;
  /**
   * 名称
   */
  name: string;
  /**
   * 子集
   */
  children: Array<Industry>;
};

export type LoginByEmailDto = {
  /**
   * 邮箱
   */
  email: string;
  /**
   * 验证码 key
   */
  key: string;
  /**
   * 验证码 code
   */
  code: string;
};

export type LoginByPhoneDto = {
  /**
   * 手机号
   */
  phone: string;
  /**
   * 验证码 key
   */
  key: string;
  /**
   * 验证码 code
   */
  code: string;
};

export type LoginDto = {
  /**
   * 可以是 username/phone/Email
   */
  login: string;
  /**
   * 密码
   */
  password: string;
};

export type LogoutDto = {
  /**
   * session key
   */
  key: string;
};

export type Namespace = {
  /**
   * 额外数据
   */
  data?: string;
  /**
   * 描述
   */
  desc?: string;
  /**
   * 标签
   */
  labels?: Array<string>;
  /**
   * 名称
   */
  name: string;
  /**
   * 命名空间的 key
   *
   * 允许的字符 ^[a-zA-Z][a-zA-Z0-9._/-]{0,30}$
   */
  key: string;
  /**
   * 所属的 namespace
   */
  ns?: string;
  /**
   * 权限
   */
  permissions?: Array<string>;
  /**
   * 是否启用
   */
  active?: boolean;
  /**
   * 默认密码
   */
  defaultPassword?: string;
  /**
   * 是否可导出
   */
  exportable?: boolean;
  /**
   * 人数
   */
  userCount?: number;
  /**
   * Entity id
   */
  id: string;
  /**
   * Entity created at when
   */
  createdAt?: string;
  /**
   * Entity updated at when
   */
  updatedAt?: string;
  /**
   * Entity created by who
   */
  createdBy?: string;
  /**
   * Entity updated by who
   */
  updatedBy?: string;
};

export type RefreshTokenDto = {
  /**
   * user id
   */
  key: string;
};

export type Region = {
  /**
   * 缩写
   */
  code: string;
  /**
   * 中文名称
   */
  nameZh: string;
  /**
   * 中文拼音
   */
  namePinyin: string;
  /**
   * 英文名称
   */
  nameEn: string;
  /**
   * 电话前缀
   */
  dialingPrefix: string;
};

export type RegisterByEmailDto = {
  /**
   * 邮箱
   */
  email: string;
  /**
   * 验证码 key
   */
  key: string;
  /**
   * 验证码 code
   */
  code: string;
  /**
   * 命名空间
   */
  ns?: string;
};

export type RegisterbyPhoneDto = {
  /**
   * 手机号
   */
  phone: string;
  /**
   * 验证码 key
   */
  key: string;
  /**
   * 验证码 code
   */
  code: string;
  /**
   * 命名空间
   */
  ns?: string;
};

export type RegisterDto = {
  /**
   * 用户名
   */
  username: string;
  /**
   * 密码
   */
  password: string;
  /**
   * 命名空间
   */
  ns?: string;
};

export type ResetPasswordDto = {
  /**
   * 密码
   */
  password?: string;
};

export type Role = {
  /**
   * role key
   */
  key: string;
  /**
   * 名称
   */
  name: string;
  /**
   * 权限
   */
  permissions: Array<string>;
  /**
   * Entity id
   */
  id: string;
  /**
   * Entity created at when
   */
  createdAt?: string;
  /**
   * Entity updated at when
   */
  updatedAt?: string;
  /**
   * Entity created by who
   */
  createdBy?: string;
  /**
   * Entity updated by who
   */
  updatedBy?: string;
};

export type SendEmailDto = {
  from: string;
  to: string;
  subject: string;
  content: string;
};

export type SendSmsDto = {
  phone: string;
  sign: string;
  template: string;
  params?: {
    [key: string]: unknown;
  };
};

export type Session = {
  /**
   * 访问控制列表
   */
  acl?: {
    [key: string]: unknown;
  };
  /**
   * 会话过期时间
   */
  expireAt: string;
  /**
   * refresh token key
   */
  key: string;
  /**
   * 用户，实际存储 uid
   */
  user: User;
  /**
   * 客户端/设备
   */
  client?: string;
  /**
   * Entity id
   */
  id: string;
  /**
   * Entity created at when
   */
  createdAt?: string;
  /**
   * Entity updated at when
   */
  updatedAt?: string;
  /**
   * Entity created by who
   */
  createdBy?: string;
  /**
   * Entity updated by who
   */
  updatedBy?: string;
};

export type SessionWithToken = {
  /**
   * 访问控制列表
   */
  acl?: {
    [key: string]: unknown;
  };
  /**
   * 会话过期时间
   */
  expireAt: string;
  /**
   * refresh token key
   */
  key: string;
  /**
   * 用户，实际存储 uid
   */
  user: User;
  /**
   * 客户端/设备
   */
  client?: string;
  /**
   * Entity id
   */
  id: string;
  /**
   * Entity created at when
   */
  createdAt?: string;
  /**
   * Entity updated at when
   */
  updatedAt?: string;
  /**
   * Entity created by who
   */
  createdBy?: string;
  /**
   * Entity updated by who
   */
  updatedBy?: string;
  /**
   * token
   */
  token: string;
  /**
   * token 过期时间
   */
  tokenExpireAt: string;
};

export type SignTokenDto = {
  /**
   * short time span string
   *
   * refs: https://github.com/vercel/ms
   *
   * eg: "2 days", "10h", "7d", "120s", "2.5 hrs", "2h", "1m", "5s", "1y", "100", "1y1m1d"
   *
   * m => minute
   * h => hour
   * d => day
   * w => week
   * M => month
   * y => year
   * s => second
   * ms => millisecond
   * 无单位 => millisecond
   */
  expiresIn: string;
  /**
   * 访问控制列表
   */
  acl?: {
    [key: string]: unknown;
  };
  /**
   * user id
   */
  uid: string;
};

export type SmsRecord = {
  status: SmsStatus;
  /**
   * 手机号
   */
  phone: string;
  /**
   * 签名
   */
  sign: string;
  /**
   * 模板
   */
  template: string;
  /**
   * 参数
   */
  params?: string;
  /**
   * 发送时间
   */
  sentAt?: string;
  /**
   * Entity id
   */
  id: string;
  /**
   * Entity created at when
   */
  createdAt?: string;
  /**
   * Entity updated at when
   */
  updatedAt?: string;
  /**
   * Entity created by who
   */
  createdBy?: string;
  /**
   * Entity updated by who
   */
  updatedBy?: string;
};

/**
 * 发送状态
 */
export type SmsStatus = 'pending' | 'sent';

export type Token = {
  /**
   * token
   */
  token: string;
  /**
   * token 过期时间
   */
  tokenExpireAt: string;
};

export type UpdateCaptchaDto = {
  /**
   * 验证码
   */
  code?: string;
  /**
   * 过期时间
   */
  expireAt?: string;
  /**
   * key
   */
  key?: string;
};

export type UpdateEmailRecordDto = {
  status?: EmailStatus;
  /**
   * 发件者
   */
  from?: string;
  /**
   * 收件者
   */
  to?: string;
  /**
   * 主题
   */
  subject?: string;
  /**
   * 内容
   */
  content?: string;
  /**
   * 发送时间
   */
  sentAt?: string;
};

export type UpdateGroupDto = {
  /**
   * 额外数据
   */
  data?: string;
  /**
   * 名称
   */
  name?: string;
  /**
   * 权限
   */
  permissions?: Array<string>;
  /**
   * 是否启用
   */
  active?: boolean;
  /**
   * 人数
   */
  userCount?: number;
};

export type UpdateNamespaceDto = {
  /**
   * 额外数据
   */
  data?: string;
  /**
   * 描述
   */
  desc?: string;
  /**
   * 标签
   */
  labels?: Array<string>;
  /**
   * 名称
   */
  name?: string;
  /**
   * 权限
   */
  permissions?: Array<string>;
  /**
   * 是否启用
   */
  active?: boolean;
  /**
   * 默认密码
   */
  defaultPassword?: string;
  /**
   * 是否可导出
   */
  exportable?: boolean;
  /**
   * 人数
   */
  userCount?: number;
};

export type UpdatePasswordDto = {
  /**
   * 旧密码
   */
  oldPassword?: string;
  /**
   * 新密码
   */
  newPassword: string;
};

export type UpdateRoleDto = {
  /**
   * 名称
   */
  name?: string;
  /**
   * 权限
   */
  permissions?: Array<string>;
};

export type UpdateSessionDto = {
  /**
   * 访问控制列表
   */
  acl?: {
    [key: string]: unknown;
  };
  /**
   * 会话过期时间
   */
  expireAt?: string;
  /**
   * 客户端/设备
   */
  client?: string;
  /**
   * 用户 ID
   */
  uid?: string;
};

export type UpdateSmsRecordDto = {
  status?: SmsStatus;
  /**
   * 手机号
   */
  phone?: string;
  /**
   * 签名
   */
  sign?: string;
  /**
   * 模板
   */
  template?: string;
  /**
   * 参数
   */
  params?: string;
  /**
   * 发送时间
   */
  sentAt?: string;
};

export type UpdateUserDto = {
  /**
   * 是否有密码
   */
  readonly hasPassword?: boolean;
  /**
   * 头像
   */
  avatar?: string;
  /**
   * 额外数据
   */
  data?: string;
  /**
   * 邮箱
   */
  email?: string;
  /**
   * 姓名
   */
  name?: string;
  identity?: string;
  /**
   * 实名认证时间
   */
  identityVerifiedAt?: string;
  /**
   * 实名认证是否通过
   */
  identityVerified?: boolean;
  /**
   * 简介
   */
  intro?: string;
  /**
   * 使用语言
   */
  language?: string;
  /**
   * 最后登录 IP
   */
  lastLoginIp?: string;
  /**
   * 最后活跃时间
   */
  lastSeenAt?: string;
  /**
   * 昵称
   */
  nickname?: string;
  /**
   * 所属命名空间
   */
  ns?: string;
  /**
   * 手机号
   */
  phone?: string;
  /**
   * 注册 IP
   */
  registerIp?: string;
  /**
   * 注册地区，存地区编号
   */
  registerRegion?: string;
  /**
   * 角色
   */
  roles?: Array<string>;
  /**
   * 是否超级管理员
   */
  super?: boolean;
  /**
   * 用户名
   */
  username?: string;
  /**
   * 员工编号
   */
  employeeId?: string;
  /**
   * 权限
   */
  permissions?: Array<string>;
  /**
   * 团队
   */
  groups?: Array<string>;
  /**
   * 最后登录时间
   */
  lastLoginAt?: string;
  /**
   * 是否启用
   */
  active?: boolean;
  /**
   * 邀请码
   */
  inviteCode?: string;
  /**
   * 状态
   */
  status?: string;
  /**
   * 过期时间
   */
  expireAt?: string;
  /**
   * 类型，支持设置多个
   */
  types?: Array<string>;
};

export type User = {
  /**
   * 密码
   */
  password?: string;
  /**
   * 是否有密码
   */
  readonly hasPassword?: boolean;
  /**
   * 头像
   */
  avatar?: string;
  /**
   * 额外数据
   */
  data?: string;
  /**
   * 邮箱
   */
  email?: string;
  /**
   * 姓名
   */
  name?: string;
  identity?: string;
  /**
   * 实名认证时间
   */
  identityVerifiedAt?: string;
  /**
   * 实名认证是否通过
   */
  identityVerified?: boolean;
  /**
   * 简介
   */
  intro?: string;
  /**
   * 使用语言
   */
  language?: string;
  /**
   * 最后登录 IP
   */
  lastLoginIp?: string;
  /**
   * 最后活跃时间
   */
  lastSeenAt?: string;
  /**
   * 昵称
   */
  nickname?: string;
  /**
   * 所属命名空间
   */
  ns?: string;
  /**
   * 手机号
   */
  phone?: string;
  /**
   * 注册 IP
   */
  registerIp?: string;
  /**
   * 注册地区，存地区编号
   */
  registerRegion?: string;
  /**
   * 角色
   */
  roles?: Array<string>;
  /**
   * 是否超级管理员
   */
  super?: boolean;
  /**
   * 用户名
   */
  username?: string;
  /**
   * 员工编号
   */
  employeeId?: string;
  /**
   * 权限
   */
  permissions?: Array<string>;
  /**
   * 团队
   */
  groups?: Array<string>;
  /**
   * 最后登录时间
   */
  lastLoginAt?: string;
  /**
   * 是否启用
   */
  active?: boolean;
  /**
   * 邀请码
   */
  inviteCode?: string;
  /**
   * 状态
   */
  status?: string;
  /**
   * 过期时间
   */
  expireAt?: string;
  /**
   * 类型，支持设置多个
   */
  types?: Array<string>;
  /**
   * Entity id
   */
  id: string;
  /**
   * Entity created at when
   */
  createdAt?: string;
  /**
   * Entity updated at when
   */
  updatedAt?: string;
  /**
   * Entity created by who
   */
  createdBy?: string;
  /**
   * Entity updated by who
   */
  updatedBy?: string;
};

export type HelloResponse = HealthCheckResult;

export type HelloError = unknown;

export type LoginData = {
  body: LoginDto;
};

export type LoginResponse = SessionWithToken;

export type LoginError = unknown;

export type LoginByEmailData = {
  body: LoginByEmailDto;
};

export type LoginByEmailResponse = SessionWithToken;

export type LoginByEmailError = unknown;

export type LoginByPhoneData = {
  body: LoginByPhoneDto;
};

export type LoginByPhoneResponse = SessionWithToken;

export type LoginByPhoneError = unknown;

export type LogoutData = {
  body: LogoutDto;
};

export type LogoutResponse = void;

export type LogoutError = unknown;

export type RegisterData = {
  body: RegisterDto;
};

export type RegisterResponse = User;

export type RegisterError = unknown;

export type RegisterByPhoneData = {
  body: RegisterbyPhoneDto;
};

export type RegisterByPhoneResponse = User;

export type RegisterByPhoneError = unknown;

export type RegisterByEmailData = {
  body: RegisterByEmailDto;
};

export type RegisterByEmailResponse = User;

export type RegisterByEmailError = unknown;

export type SignTokenData = {
  body: SignTokenDto;
};

export type SignTokenResponse = Token;

export type SignTokenError = unknown;

export type RefreshData = {
  body: RefreshTokenDto;
};

export type RefreshResponse = SessionWithToken;

export type RefreshError = unknown;

export type CleanupAllDataResponse = void;

export type CleanupAllDataError = unknown;

export type CreateUserData = {
  body: CreateUserDto;
};

export type CreateUserResponse = User;

export type CreateUserError = unknown;

export type ListUsersData = {
  query?: {
    /**
     * 分页大小
     */
    _limit?: number;
    /**
     * 分页偏移
     */
    _offset?: number;
    /**
     * 排序参数
     */
    _sort?:
      | 'createdAt'
      | '-createdAt'
      | 'updatedAt'
      | '-updatedAt'
      | 'lastLoginAt'
      | '-lastLoginAt'
      | 'expireAt'
      | '-expireAt';
    /**
     * 是否启用
     */
    active?: boolean;
    /**
     * 邮箱
     */
    email?: string;
    /**
     * 过期时间大于该时间
     */
    expireAt_gte?: string;
    /**
     * 过期时间小于该时间
     */
    expireAt_lte?: string;
    /**
     * 团队
     */
    groups?: Array<string>;
    /**
     * 按 id 筛选
     */
    id?: Array<string>;
    /**
     * 姓名
     */
    name?: string;
    /**
     * 名称 模糊查询
     */
    name_like?: string;
    /**
     * 昵称 模糊查询
     */
    nickname_like?: string;
    /**
     * 所属命名空间的 tree 查询
     */
    ns_tree?: string;
    /**
     * 手机号
     */
    phone?: string;
    /**
     * 注册地区，存地区编号
     */
    registerRegion?: string;
    /**
     * 角色
     */
    roles?: Array<string>;
    /**
     * 状态
     */
    status?: string;
    /**
     * 类型，支持设置多个
     */
    types?: Array<string>;
    /**
     * 用户名
     */
    username?: string;
    /**
     * 用户名 模糊查询
     */
    username_like?: string;
  };
};

export type ListUsersResponse = Array<User>;

export type ListUsersError = unknown;

export type GetUserData = {
  path: {
    /**
     * User id
     */
    userId: string;
  };
};

export type GetUserResponse = User;

export type GetUserError = unknown;

export type UpdateUserData = {
  body: UpdateUserDto;
  path: {
    userId: string;
  };
};

export type UpdateUserResponse = User;

export type UpdateUserError = unknown;

export type DeleteUserData = {
  path: {
    userId: string;
  };
};

export type DeleteUserResponse = void;

export type DeleteUserError = unknown;

export type UpsertUserByEmployeeIdData = {
  body: UpdateUserDto;
  path: {
    userEmployeeId: string;
  };
};

export type UpsertUserByEmployeeIdResponse = User;

export type UpsertUserByEmployeeIdError = unknown;

export type VerifyIdentityData = {
  path: {
    userId: string;
  };
};

export type VerifyIdentityResponse = User;

export type VerifyIdentityError = unknown;

export type ResetPasswordData = {
  body: ResetPasswordDto;
  path: {
    userId: string;
  };
};

export type ResetPasswordResponse = void;

export type ResetPasswordError = unknown;

export type UpdatePasswordData = {
  body: UpdatePasswordDto;
  path: {
    userId: string;
  };
};

export type UpdatePasswordResponse = void;

export type UpdatePasswordError = unknown;

export type CreateNamespaceData = {
  body: CreateNamespaceDto;
};

export type CreateNamespaceResponse = Namespace;

export type CreateNamespaceError = unknown;

export type ListNamespacesData = {
  query?: {
    /**
     * 分页大小
     */
    _limit?: number;
    /**
     * 分页偏移
     */
    _offset?: number;
    /**
     * 排序参数
     */
    _sort?:
      | 'createdAt'
      | '-createdAt'
      | 'updatedAt'
      | '-updatedAt'
      | 'key'
      | '-key'
      | 'name'
      | '-name';
    /**
     * 命名空间的 key
     *
     * 允许的字符 ^[a-zA-Z][a-zA-Z0-9._/-]{0,30}$
     */
    key?: string;
    /**
     * key tree 查询
     */
    key_tree?: string;
    /**
     * 标签
     */
    labels?: Array<string>;
    /**
     * 名称 模糊查询
     */
    name_like?: string;
    /**
     * 所属命名空间 tree 查询
     */
    ns_tree?: string;
  };
};

export type ListNamespacesResponse = Array<Namespace>;

export type ListNamespacesError = unknown;

export type GetNamespaceData = {
  path: {
    /**
     * Namespace id or key, if key should encodeURIComponent
     */
    namespaceIdOrKey: string;
  };
};

export type GetNamespaceResponse = Namespace;

export type GetNamespaceError = unknown;

export type UpdateNamespaceData = {
  body: UpdateNamespaceDto;
  path: {
    namespaceIdOrKey: string;
  };
};

export type UpdateNamespaceResponse = Namespace;

export type UpdateNamespaceError = unknown;

export type DeleteNamespaceData = {
  path: {
    namespaceId: string;
  };
};

export type DeleteNamespaceResponse = void;

export type DeleteNamespaceError = unknown;

export type CreateSessionData = {
  body: CreateSessionDto;
};

export type CreateSessionResponse = Session;

export type CreateSessionError = unknown;

export type ListSessionsData = {
  query?: {
    /**
     * 分页大小
     */
    _limit?: number;
    /**
     * 分页偏移
     */
    _offset?: number;
    /**
     * 排序参数
     */
    _sort?: 'createdAt' | '-createdAt' | 'updatedAt' | '-updatedAt' | 'expireAt' | '-expireAt';
    /**
     * 客户端/设备
     */
    client?: string;
    /**
     * 用 key 进行查询
     */
    key?: string;
    /**
     * 用户 ID
     */
    uid?: string;
  };
};

export type ListSessionsResponse = Array<Session>;

export type ListSessionsError = unknown;

export type GetSessionData = {
  path: {
    sessionId: string;
  };
};

export type GetSessionResponse = Session;

export type GetSessionError = unknown;

export type UpdateSessionData = {
  body: UpdateSessionDto;
  path: {
    sessionId: string;
  };
};

export type UpdateSessionResponse = Session;

export type UpdateSessionError = unknown;

export type DeleteSessionData = {
  path: {
    sessionId: string;
  };
};

export type DeleteSessionResponse = void;

export type DeleteSessionError = unknown;

export type CreateGroupData = {
  body: CreateGroupDto;
};

export type CreateGroupResponse = Group;

export type CreateGroupError = unknown;

export type ListGroupsData = {
  query?: {
    /**
     * 分页大小
     */
    _limit?: number;
    /**
     * 分页偏移
     */
    _offset?: number;
    /**
     * 排序参数
     */
    _sort?: 'createdAt' | '-createdAt' | 'updatedAt' | '-updatedAt';
    /**
     * 是否启用
     */
    active?: boolean;
    /**
     * 名称
     */
    name?: string;
    /**
     * 名称 模糊查询
     */
    name_like?: string;
  };
};

export type ListGroupsResponse = Array<Group>;

export type ListGroupsError = unknown;

export type GetGroupData = {
  path: {
    /**
     * Group id or name, if name should encodeURIComponent
     */
    groupIdOrName: string;
  };
};

export type GetGroupResponse = Group;

export type GetGroupError = unknown;

export type UpdateGroupData = {
  body: UpdateGroupDto;
  path: {
    groupId: string;
  };
};

export type UpdateGroupResponse = Group;

export type UpdateGroupError = unknown;

export type DeleteGroupData = {
  path: {
    groupId: string;
  };
};

export type DeleteGroupResponse = void;

export type DeleteGroupError = unknown;

export type CreateCaptchaData = {
  body: CreateCaptchaDto;
};

export type CreateCaptchaResponse = Captcha;

export type CreateCaptchaError = unknown;

export type ListCaptchasData = {
  query?: {
    /**
     * 分页大小
     */
    _limit?: number;
    /**
     * 分页偏移
     */
    _offset?: number;
    /**
     * 排序参数
     */
    _sort?: 'createdAt' | '-createdAt' | 'updatedAt' | '-updatedAt' | 'expireAt' | '-expireAt';
    /**
     * 验证码
     */
    code?: string;
    /**
     * key
     */
    key?: string;
  };
};

export type ListCaptchasResponse = Array<Captcha>;

export type ListCaptchasError = unknown;

export type GetCaptchaData = {
  path: {
    captchaId: string;
  };
};

export type GetCaptchaResponse = Captcha;

export type GetCaptchaError = unknown;

export type UpdateCaptchaData = {
  body: UpdateCaptchaDto;
  path: {
    captchaId: string;
  };
};

export type UpdateCaptchaResponse = Captcha;

export type UpdateCaptchaError = unknown;

export type DeleteCaptchaData = {
  path: {
    captchaId: string;
  };
};

export type DeleteCaptchaResponse = void;

export type DeleteCaptchaError = unknown;

export type SendEmailData = {
  body: SendEmailDto;
};

export type SendEmailResponse = void;

export type SendEmailError = unknown;

export type CreateEmailRecordData = {
  body: CreateEmailRecordDto;
};

export type CreateEmailRecordResponse = EmailRecord;

export type CreateEmailRecordError = unknown;

export type ListEmailRecordsData = {
  query?: {
    /**
     * 分页大小
     */
    _limit?: number;
    /**
     * 分页偏移
     */
    _offset?: number;
    /**
     * 排序参数
     */
    _sort?: 'createdAt' | '-createdAt' | 'updatedAt' | '-updatedAt' | 'sentAt' | '-sentAt';
    /**
     * 创建时间大于该时间
     */
    createdAt_gt?: string;
    /**
     * 创建时间小于该时间
     */
    createdAt_lt?: string;
    /**
     * 发件者
     */
    from?: string;
    /**
     * 发送时间大于该时间
     */
    sentAt_gt?: string;
    /**
     * 发送时间小于该时间
     */
    sentAt_lt?: string;
    /**
     * 发送状态
     */
    status?: EmailStatus;
    /**
     * 收件者
     */
    to?: string;
  };
};

export type ListEmailRecordsResponse = Array<EmailRecord>;

export type ListEmailRecordsError = unknown;

export type GetEmailRecordData = {
  path: {
    /**
     * Email record id
     */
    emailRecordId: string;
  };
};

export type GetEmailRecordResponse = EmailRecord;

export type GetEmailRecordError = unknown;

export type UpdateEmailRecordData = {
  body: UpdateEmailRecordDto;
  path: {
    emailRecordId: string;
  };
};

export type UpdateEmailRecordResponse = EmailRecord;

export type UpdateEmailRecordError = unknown;

export type DeleteEmailRecordData = {
  path: {
    emailRecordId: string;
  };
};

export type DeleteEmailRecordResponse = void;

export type DeleteEmailRecordError = unknown;

export type SendSmsData = {
  body: SendSmsDto;
};

export type SendSmsResponse = void;

export type SendSmsError = unknown;

export type CreateSmsRecordData = {
  body: CreateSmsRecordDto;
};

export type CreateSmsRecordResponse = SmsRecord;

export type CreateSmsRecordError = unknown;

export type ListSmsRecordsData = {
  query?: {
    /**
     * 分页大小
     */
    _limit?: number;
    /**
     * 分页偏移
     */
    _offset?: number;
    /**
     * 排序参数
     */
    _sort?: 'createdAt' | '-createdAt' | 'updatedAt' | '-updatedAt' | 'sentAt' | '-sentAt';
    /**
     * 创建时间大于该时间
     */
    createdAt_gt?: string;
    /**
     * 创建时间小于该时间
     */
    createdAt_lt?: string;
    /**
     * 手机号
     */
    phone?: string;
    /**
     * 发送时间大于该时间
     */
    sentAt_gt?: string;
    /**
     * 发送时间小于该时间
     */
    sentAt_lt?: string;
    /**
     * 签名
     */
    sign?: string;
    /**
     * 发送状态
     */
    status?: SmsStatus;
  };
};

export type ListSmsRecordsResponse = Array<SmsRecord>;

export type ListSmsRecordsError = unknown;

export type GetSmsRecordData = {
  path: {
    /**
     * Sms record id
     */
    smsRecordId: string;
  };
};

export type GetSmsRecordResponse = SmsRecord;

export type GetSmsRecordError = unknown;

export type UpdateSmsRecordData = {
  body: UpdateSmsRecordDto;
  path: {
    smsRecordId: string;
  };
};

export type UpdateSmsRecordResponse = SmsRecord;

export type UpdateSmsRecordError = unknown;

export type DeleteSmsRecordData = {
  path: {
    smsRecordId: string;
  };
};

export type DeleteSmsRecordResponse = void;

export type DeleteSmsRecordError = unknown;

export type ListIndustriesResponse = Array<Industry>;

export type ListIndustriesError = unknown;

export type ListRegionsResponse = Array<Region>;

export type ListRegionsError = unknown;

export type CreateRoleData = {
  body: CreateRoleDto;
};

export type CreateRoleResponse = Role;

export type CreateRoleError = unknown;

export type ListRolesData = {
  query?: {
    /**
     * 分页大小
     */
    _limit?: number;
    /**
     * 分页偏移
     */
    _offset?: number;
    /**
     * 排序参数
     */
    _sort?: 'createdAt' | '-createdAt' | 'updatedAt' | '-updatedAt';
    /**
     * role key
     */
    key?: string;
    /**
     * 名称
     */
    name?: string;
    /**
     * 名称 模糊查询
     */
    name_like?: string;
  };
};

export type ListRolesResponse = Array<Role>;

export type ListRolesError = unknown;

export type GetRoleData = {
  path: {
    /**
     * Role id or key
     */
    roleIdOrKey: string;
  };
};

export type GetRoleResponse = Role;

export type GetRoleError = unknown;

export type UpdateRoleData = {
  body: UpdateRoleDto;
  path: {
    roleId: string;
  };
};

export type UpdateRoleResponse = Role;

export type UpdateRoleError = unknown;

export type DeleteRoleData = {
  path: {
    roleId: string;
  };
};

export type DeleteRoleResponse = void;

export type DeleteRoleError = unknown;
